### ISSUE TITLE
Feature: User can fill formatted textbox

### ISSUE THREAD

**Issue by skylarshaffer** [skylarshaffer/alterplates#1]
## ⚙️ Feature

User can enter up to 7 characters in a textbox formatted like a California state license plate.

## 📐 Functionality

At this point, the feature will be incredibly straightforward. Textbox will be capped at 7 characters, and will otherwise perform like a standard textbox. Most of this first feature is design.

## 🖼️ Wireframes

![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/3f56031f-1a44-4f47-ba35-e2ab6776eca9)
![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/1ab1e11c-4dc3-4a48-9fd0-77abbca021d2)

## ✅ Task List

- **Create**
  - [x] Navbar.
  - [x] H1.
  - [x] license-plate ~~-mobile~~:
    ![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/f3045daa-6512-45c3-ab05-119204855e53)
  - [x] Outer rectangle 
  - [x] Inner rectangle
  - [x] MO Square
  - [x] California vector
  - [x] YR Square
  - [x] Plate number textbox
  - [x] CA DMV URL
  - ~~All 3 license plate items based upon license-plate-mobile:~~
    - ~~license-plate-small (50%)~~
      - ~~Read-only text~~
    - ~~license-plate-mobile (100%)~~
    - ~~license-plate-desktop (150%)~~
- **Code**
  - ~~Add desktop responsiveness, switch license plate frames accordingly.~~
  - [x] Force any typing to always affect the one non-small plate visible, either by input listening or by forcing focus.
  - ~~Unify mobile and desktop plates content either by view swapping, CSS attribute changes, or input listening.~~
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by skylarshaffer** [comment]
Number of strikethroughs added due to simplification since original pitch. Used a ton of relative calculations for license plate frame to eliminate the need for unique, view-swapped frames. This means no input unification for desktop and mobile input frame, as they are the same frame.
Unique, small frames not needed, as css rules will be determined by parent container, in this case "suggestions", the only container that will contain frames that are not the single, primary textbox frame.

**Comment by skylarshaffer** [comment]
Completed pull, merged with main.
https://github.com/skylarshaffer/front-end-project/pull/5
