### ISSUE TITLE
Feature: User will see suggestions on each input character

### ISSUE THREAD

**Issue by skylarshaffer** [skylarshaffer/alterplates#2]
## ⚙️ Feature

User can generate a list of suggested alternate plates by entering any characters.

## 📐 Functionality

On each input character, 10 suggestions (9 visible on desktop) for alternate license plate will be generated. Each set of suggestions will be cleared and regenerated on each subsequent character entered.

## 🖼️ Wireframes

![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/3313abc3-9151-4b0a-8fdf-24fb9c9c61ab)
![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/a58386e6-a947-4184-8740-de7df172e330)

## ✅ Task List

- **Create**
  - [x] Suggestions div beneath main plate with:
    - [x] 10 empty plates
    - [x] Responsiveness:
      - [x] 10th plate should hide on desktop.
      - [x] Width of suggestions div should match main plate width.
      - [x] Width of suggestions plates themselves should therefore be: [suggestions div width - space between(x1 for mobile, x2 for desktop)]
      - Rows should be:
        - [x] 2-wide on mobile
        - [x] 3-wide on desktop

- **Code**
  - [x] Add Datamuse API call function with one parameter, current value of main plate:
    - [ ] Generate 10 suggestions with as many HTTP requests as necessary and overwrite current values of 10 plates.
      - All 10 suggestions must be:
        - [x] Unique and not match main plate
        - [x] <8 characters, only:
          - [x] Letters
          - [x] Numbers
          - [x] Spaces
        - [x] Meaningfully similar to main plate
      - ~~Intelligently rate limit:~~
        - ~~At the start of each request batch (however many requests are needed to populate plates), check if a request was made .5s ago.~~
        - ~~If no request in last .5s, go ahead.~~
        - ~~If request in last .5s, add to queue.~~
        - ~~If queue already populated, overwrite that request with this new batch.~~
  - [x] Create event listener for changes to textbox value.
    - [x] Get current value.
      - [x] ~~If empty, hide all 10 suggestions.~~
      - [x] If not, send as argument to Datamuse API call function.
  - [x] Cache suggestions and use cached suggestions if prompt is ever seen more than once.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by skylarshaffer** [comment]
Changed suggestions hide from listener to pure CSS.

**Comment by skylarshaffer** [comment]
Removed intelligent rate limiting as it proved to not be necessary.

**Comment by skylarshaffer** [comment]
Added caching to feature as it exists in the application.

**Comment by skylarshaffer** [comment]
Completed pull, merged with main. Still some work needed but moving on for now and will come back.
https://github.com/skylarshaffer/alterplates/pull/6
