### ISSUE TITLE
Feature: User can add a suggested plate to "Favorites"

### ISSUE THREAD

**Issue by skylarshaffer** [skylarshaffer/alterplates#3]
## ⚙️ Feature

User interact to attempt to add a suggested plate to favorites.

## 📐 Functionality

User can click or tap any plate suggestion to be prompted to add to favorites. The user can click anywhere to close the prompt.
Favorites does not yet exist and therefore will not be added to. This feature is simply the process of adding, without the resulting entry.

## 🖼️ Wireframes

![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/9de4d77e-9b64-44b7-9e29-f0c9ca38c741)
![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/85ffbcab-7a34-4aee-bfae-51b3cbaa9c8f)

## ✅ Task List

- **Create**
  - [x] "Favorite button" dialog for adding to favorites

- **Code**
  - [x] Add event listener to suggestions div for click, ~~right click~~, tap, or~~ hold~~.
    - [x] Get current target nearest plate (selected plate).
    - [x] Open modal dialog above selected plate, shade and blur all but:
      - modal
      - selected plate
      - navbar
    - [x] If dialog is clicked or tapped, exit modal.
    - [x] If click or tap is not on dialog, exit modal.

- **Clean Up**
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by skylarshaffer** [comment]
Completed pull, merged with main.
https://github.com/skylarshaffer/alterplates/pull/7
