### ISSUE TITLE
Feature: User can interact with saved "Favorites"

### ISSUE THREAD

**Issue by skylarshaffer** [skylarshaffer/alterplates#4]
## ⚙️ Feature

User can save suggestions to favorites, and interact with their stored favorites through the "Favorites" menu.

## 📐 Functionality

User can add plates to their "Favorites" menu by clicking or tapping the star when interacting with a suggestion. Clicking anywhere other than the star will still close the dialog, but will not add to favorites.
User can view their "Favorites" menu using the top right button (or always visible on desktop). User can click or tap any stored suggestion inside this menu to be prompted to delete from favorites. The user can click anywhere to close the prompt, and clicking the "Delete" button will remove the suggestion from the "Favorites" menu.

## 🖼️ Wireframes

![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/e0c92fd5-0c36-4955-a618-dec9eb684edd)
![image](https://github.com/skylarshaffer/front-end-project/assets/161654841/d537258d-c744-4b33-a096-40a2d984a2d0)

## ✅ Task List

- **Create**
  - [x] Favorites bar:
    - [x] Desktop: ~~always visible~~ open by default
    - [x] Mobile: ~~Top right button to open side menu~~ closed by default
  - [x] Make favorites menu responsive: ~~always as wide as small plate width + margin~~ still needs work
  - [x] Favorites div in favorites bar
  - [x] Delete button
  - [x] "Delete button" dialog for removing from favorites

- **Code**
  - [x] Modify suggestions div event listener for click, right click, tap, or hold.
    - [x] If dialog is clicked or tapped, add plate to favorites and exit modal.
    - [x] If click or tap is not on dialog, exit modal.
  - [x] Add event listener to favorites div for click, right click, tap, or hold.
    - [x] Get current target nearest plate (selected plate).
    - [x] Open modal dialog above selected plate, shade and blur all but:
      - modal
      - selected plate
      - navbar
    - [x] If dialog is clicked or tapped, remove from favorites and exit modal.
    - [x] If click or tap is not on dialog, exit modal.

- **Clean Up**
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
